DROP SEQUENCE client_id_seq;
DROP SEQUENCE case_id_seq;
DROP SEQUENCE agent_id_seq;
DROP SEQUENCE project_id_seq;
DROP SEQUENCE invoice_id_seq;
DROP SEQUENCE transaction_id_seq;

CREATE SEQUENCE client_id_seq
START WITH 1
INCREMENT BY 1
NOMAXVALUE
MINVALUE 1
CACHE 100
ORDER;

CREATE SEQUENCE case_id_seq
START WITH 1
INCREMENT BY 1
NOMAXVALUE
MINVALUE 1
CACHE 100
ORDER;

CREATE SEQUENCE agent_id_seq
START WITH 1
INCREMENT BY 1
NOMAXVALUE
MINVALUE 1
CACHE 100
ORDER;

CREATE SEQUENCE project_id_seq
START WITH 1
INCREMENT BY 1
NOMAXVALUE
MINVALUE 1
CACHE 100
ORDER;

CREATE SEQUENCE invoice_id_seq
START WITH 1
INCREMENT BY 1
NOMAXVALUE
MINVALUE 1
CACHE 100
ORDER;

CREATE SEQUENCE transaction_id_seq
START WITH 1
INCREMENT BY 1
NOMAXVALUE
MINVALUE 1
CACHE 100
ORDER;
